version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: earn-bot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: superteam_earn_bot
    ports:
      - "35432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    container_name: earn-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: earn_database
      MYSQL_USER: earn_user
      MYSQL_PASSWORD: earn_pass123
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local